mysql: &mysql
  adapter: mysql2
  charset: utf8
  collation: utf8_general_ci
  reconnect: false
  pool: 5
  port: 3306
  
mac: &mac
  socket: /tmp/mysql.sock
  host: localhost                            	
  username: root
  password:

ubuntu: &ubuntu
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  username: root
  password: 

development:
  <<: *mysql
  <<: *mac
  database: we_are_the_word_development
  
test:
  <<: *mysql
  <<: *mac
  database: we_are_the_word_test

production:
  <<: *mysql
  <<: *ubuntu 
  database: we_are_the_word_production
